/**
 * Self-hosts the newsprint UI fonts.
 *
 * Copies the woff2 files we actually use out of the @fontsource packages into
 * public/fonts, and regenerates src/styles/fonts.generated.css with the exact
 * unicode-range declarations the packages ship. The ranges matter: they let the
 * browser skip latin-ext entirely on an English page.
 *
 * The editor's document font catalogue still comes from Google — those are
 * fonts the user picks for their PDF, not chrome, and there are fourteen of them.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outDir = path.join(root, "public/fonts");
const outCss = path.join(root, "src/styles/fonts.generated.css");

/**
 * Bodoni Moda keeps the optical-size axis — the hairlines at masthead sizes are
 * the whole point. Newsreader only ever varies weight here, so the wght-only
 * cut saves well over half the bytes.
 */
const FACES = [
  {
    family: "Bodoni Moda",
    pkg: "@fontsource-variable/bodoni-moda",
    css: "standard.css",
    file: "bodoni-moda-latin-standard-normal",
  },
  {
    family: "Bodoni Moda",
    pkg: "@fontsource-variable/bodoni-moda",
    css: "standard.css",
    file: "bodoni-moda-latin-ext-standard-normal",
  },
  {
    family: "Bodoni Moda",
    pkg: "@fontsource-variable/bodoni-moda",
    css: "standard-italic.css",
    file: "bodoni-moda-latin-standard-italic",
  },
  {
    family: "Bodoni Moda",
    pkg: "@fontsource-variable/bodoni-moda",
    css: "standard-italic.css",
    file: "bodoni-moda-latin-ext-standard-italic",
  },
  {
    family: "Newsreader",
    pkg: "@fontsource-variable/newsreader",
    css: "wght.css",
    file: "newsreader-latin-wght-normal",
  },
  {
    family: "Newsreader",
    pkg: "@fontsource-variable/newsreader",
    css: "wght.css",
    file: "newsreader-latin-ext-wght-normal",
  },
  {
    family: "Newsreader",
    pkg: "@fontsource-variable/newsreader",
    css: "wght-italic.css",
    file: "newsreader-latin-wght-italic",
  },
  {
    family: "Newsreader",
    pkg: "@fontsource-variable/newsreader",
    css: "wght-italic.css",
    file: "newsreader-latin-ext-wght-italic",
  },
  // The per-subset stylesheets drop unicode-range, so read the combined index.
  {
    family: "Courier Prime",
    pkg: "@fontsource/courier-prime",
    css: "index.css",
    file: "courier-prime-latin-400-normal",
  },
  {
    family: "Courier Prime",
    pkg: "@fontsource/courier-prime",
    css: "index.css",
    file: "courier-prime-latin-ext-400-normal",
  },
  {
    family: "Courier Prime",
    pkg: "@fontsource/courier-prime",
    css: "700.css",
    file: "courier-prime-latin-700-normal",
  },
  {
    family: "Courier Prime",
    pkg: "@fontsource/courier-prime",
    css: "700.css",
    file: "courier-prime-latin-ext-700-normal",
  },
];

/** Pulls the @font-face block that references `file` out of a package stylesheet. */
function readFace(pkg, cssName, file) {
  const cssPath = path.join(root, "node_modules", pkg, cssName);
  const css = fs.readFileSync(cssPath, "utf8");

  const block = css.split("@font-face").find((chunk) => chunk.includes(`/files/${file}.woff2`));
  if (!block) throw new Error(`No @font-face for ${file} in ${pkg}/${cssName}`);

  const pick = (prop) => {
    const m = block.match(new RegExp(`${prop}:\\s*([^;]+);`));
    if (!m) throw new Error(`Missing ${prop} for ${file}`);
    return m[1].trim();
  };

  return {
    style: pick("font-style"),
    weight: pick("font-weight"),
    unicodeRange: pick("unicode-range"),
    format: block.includes("woff2-variations") ? "woff2-variations" : "woff2",
    source: path.join(root, "node_modules", pkg, "files", `${file}.woff2`),
  };
}

fs.rmSync(outDir, { recursive: true, force: true });
fs.mkdirSync(outDir, { recursive: true });

const blocks = [];
let bytes = 0;

for (const face of FACES) {
  const { style, weight, unicodeRange, format, source } = readFace(face.pkg, face.css, face.file);
  const fileName = `${face.file}.woff2`;

  fs.copyFileSync(source, path.join(outDir, fileName));
  bytes += fs.statSync(source).size;

  blocks.push(
    [
      "@font-face {",
      `  font-family: "${face.family}";`,
      `  font-style: ${style};`,
      `  font-weight: ${weight};`,
      "  font-display: swap;",
      `  src: url("/public/fonts/${fileName}") format("${format}");`,
      `  unicode-range: ${unicodeRange};`,
      "}",
    ].join("\n"),
  );
}

const header = [
  "/*",
  " * GENERATED by scripts/build-fonts.mjs — do not edit by hand.",
  " * Run `npm run build:fonts` after changing the face list there.",
  " */",
  "",
].join("\n");

fs.writeFileSync(outCss, `${header}${blocks.join("\n\n")}\n`);

console.log(
  `fonts: ${FACES.length} faces → public/fonts (${(bytes / 1024).toFixed(0)} KB on disk)`,
);
console.log(`wrote ${path.relative(root, outCss)}`);
